version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
        - '5432'
    volumes:
        - ts-docker:/var/lib/postgresql/data

  ts-docker:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
        - postgres
    ports:
        - '7777:7777' 
volumes:
    ts-docker:
